build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go build
    - go test

publish:
  docker:
    username: jackspirou
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: jackspirou/drone-hipchat
    when:
      branch: master

plugin:
  name: HipChat
  desc: Send build status notifications to your HipChat room.
  type: notify
  image: jackspirou/drone-hipchat
  labels:
    - chat
    - messaging
